import { CityConfig, Place, ReportCategory } from "./types";

export const CITIES: Record<string, CityConfig> = {
  Pune: {
    name: "Pune",
    state: "Maharashtra",
    country: "India",
    lat: 18.5204,
    lon: 73.8567,
    zoom: 13,
    bbox: [18.42, 73.74, 18.63, 73.98],
  },
  Mumbai: {
    name: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: 19.076,
    lon: 72.8777,
    zoom: 12,
  },
  Bengaluru: {
    name: "Bengaluru",
    state: "Karnataka",
    country: "India",
    lat: 12.9716,
    lon: 77.5946,
    zoom: 12,
  },
};

export const DEFAULT_CITY = CITIES.Pune;

export const REPORT_CATEGORIES: {
  id: ReportCategory;
  label: string;
  description: string;
  badgeColor: string;
}[] = [
  {
    id: "pothole",
    label: "Pothole & Damaged Road",
    description: "Road depressions, asphalt cracking, deep craters",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-300",
  },
  {
    id: "waterlogging",
    label: "Waterlogging & Flooding",
    description: "Stagnant monsoon water, choked storm drains, flooded roads",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-300",
  },
  {
    id: "streetlight",
    label: "Broken Streetlight",
    description: "Flickering, non-functioning, or damaged public street lamps",
    badgeColor: "bg-yellow-100 text-yellow-800 border-yellow-300",
  },
  {
    id: "obstruction",
    label: "Road Obstruction",
    description: "Fallen trees, abandoned debris, illegal road barricades",
    badgeColor: "bg-red-100 text-red-800 border-red-300",
  },
  {
    id: "cleanliness",
    label: "Cleanliness & Garbage",
    description: "Overflowing dumpsters, unattended street garbage, littering",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
  },
  {
    id: "other",
    label: "Other Civic Problem",
    description: "General infrastructure, footpaths, traffic signal failure",
    badgeColor: "bg-purple-100 text-purple-800 border-purple-300",
  },
];

export const PLACE_CATEGORIES = [
  { id: "all", label: "All Categories" },
  { id: "tourist", label: "Tourist Attractions" },
  { id: "historical", label: "Historical Landmarks" },
  { id: "restaurant", label: "Restaurants & Cafes" },
  { id: "park", label: "Parks & Public Spaces" },
  { id: "hotel", label: "Hotels & Stays" },
] as const;

// Curated high-accuracy Pune places dataset for fallback / demo mode
export const CURATED_PUNE_PLACES: Place[] = [
  {
    id: "pune-hist-1",
    name: "Shaniwar Wada",
    category: "historical",
    categoryLabel: "Historical Landmark",
    address: "Shaniwar Peth, Bajirao Road, Pune 411030",
    latitude: 18.5196,
    longitude: 73.8553,
    source: "curated",
    rawType: "fortress",
  },
  {
    id: "pune-hist-2",
    name: "Aga Khan Palace",
    category: "historical",
    categoryLabel: "Historical Landmark",
    address: "Pune-Nagar Road, Kalyani Nagar, Pune 411014",
    latitude: 18.5524,
    longitude: 73.9015,
    source: "curated",
    rawType: "palace",
  },
  {
    id: "pune-hist-3",
    name: "Sinhagad Fort",
    category: "historical",
    categoryLabel: "Historical Landmark",
    address: "Sinhagad Ghat Road, Thoptewadi, Pune 411025",
    latitude: 18.3663,
    longitude: 73.7558,
    source: "curated",
    rawType: "fort",
  },
  {
    id: "pune-tourist-1",
    name: "Raja Dinkar Kelkar Museum",
    category: "tourist",
    categoryLabel: "Tourist Attraction",
    address: "1377-78, Natu Baug, Off Bajirao Road, Shukrawar Peth, Pune 411002",
    latitude: 18.5108,
    longitude: 73.8543,
    source: "curated",
    rawType: "museum",
  },
  {
    id: "pune-tourist-2",
    name: "Pataleshwar Cave Temple",
    category: "tourist",
    categoryLabel: "Tourist Attraction",
    address: "Jangali Maharaj Road, Shivajinagar, Pune 411005",
    latitude: 18.5284,
    longitude: 73.8499,
    source: "curated",
    rawType: "cave_temple",
  },
  {
    id: "pune-tourist-3",
    name: "Parvati Hill & Temple",
    category: "tourist",
    categoryLabel: "Tourist Attraction",
    address: "Parvati Paytha, Pune 411009",
    latitude: 18.4975,
    longitude: 73.8475,
    source: "curated",
    rawType: "viewpoint",
  },
  {
    id: "pune-park-1",
    name: "Pu La Deshpande Garden (Okayama Friendship Garden)",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Sinhagad Road, Dattawadi, Pune 411030",
    latitude: 18.4947,
    longitude: 73.8344,
    source: "curated",
    rawType: "garden",
  },
  {
    id: "pune-park-2",
    name: "Saras Baug",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Sadashiv Peth, Near Sanas Ground, Pune 411030",
    latitude: 18.5009,
    longitude: 73.8536,
    source: "curated",
    rawType: "garden",
  },
  {
    id: "pune-park-3",
    name: "Empress Botanical Garden",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Near Race Course, Camp, Pune 411001",
    latitude: 18.5107,
    longitude: 73.8967,
    source: "curated",
    rawType: "botanical_garden",
  },
  {
    id: "pune-rest-1",
    name: "Vaishali Restaurant",
    category: "restaurant",
    categoryLabel: "Restaurant & Cafe",
    address: "1218/1, FC Road, Shivajinagar, Pune 411004",
    latitude: 18.5186,
    longitude: 73.8415,
    source: "curated",
    rawType: "restaurant",
  },
  {
    id: "pune-rest-2",
    name: "Goodluck Cafe",
    category: "restaurant",
    categoryLabel: "Restaurant & Cafe",
    address: "Fergusson College Road, Deccan Gymkhana, Pune 411004",
    latitude: 18.5173,
    longitude: 73.8419,
    source: "curated",
    rawType: "cafe",
  },
  {
    id: "pune-rest-3",
    name: "Kayani Bakery",
    category: "restaurant",
    categoryLabel: "Restaurant & Cafe",
    address: "6, East Street, Camp, Pune 411001",
    latitude: 18.5144,
    longitude: 73.8812,
    source: "curated",
    rawType: "bakery",
  },
  {
    id: "pune-hotel-1",
    name: "The Ritz-Carlton Pune",
    category: "hotel",
    categoryLabel: "Hotel & Stay",
    address: "Golf Course Square, Airport Rd, Yerawada, Pune 411006",
    latitude: 18.5583,
    longitude: 73.8931,
    source: "curated",
    rawType: "hotel",
  },
  {
    id: "pune-hotel-2",
    name: "JW Marriott Hotel Pune",
    category: "hotel",
    categoryLabel: "Hotel & Stay",
    address: "Senapati Bapat Rd, Shivajinagar, Pune 411053",
    latitude: 18.5326,
    longitude: 73.8299,
    source: "curated",
    rawType: "hotel",
  },
];

export const CURATED_MUMBAI_PLACES: Place[] = [
  {
    id: "mum-hist-1",
    name: "Gateway of India",
    category: "historical",
    categoryLabel: "Historical Landmark",
    address: "Apollo Bandar, Colaba, Mumbai 400001",
    latitude: 18.922,
    longitude: 72.8347,
    source: "curated",
    rawType: "monument",
  },
  {
    id: "mum-tourist-1",
    name: "Marine Drive Promenade",
    category: "tourist",
    categoryLabel: "Tourist Attraction",
    address: "Netaji Subhash Chandra Bose Road, Mumbai 400020",
    latitude: 18.9432,
    longitude: 72.823,
    source: "curated",
    rawType: "promenade",
  },
  {
    id: "mum-park-1",
    name: "Hanging Gardens (Pherozeshah Mehta Gardens)",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Ridge Rd, Simla Nagar, Malabar Hill, Mumbai 400006",
    latitude: 18.9566,
    longitude: 72.8052,
    source: "curated",
    rawType: "garden",
  },
  {
    id: "mum-rest-1",
    name: "Leopold Cafe & Bar",
    category: "restaurant",
    categoryLabel: "Restaurant & Cafe",
    address: "Colaba Causeway, Apollo Bandar, Colaba, Mumbai 400001",
    latitude: 18.9229,
    longitude: 72.8317,
    source: "curated",
    rawType: "cafe",
  },
  {
    id: "mum-hotel-1",
    name: "The Taj Mahal Palace",
    category: "hotel",
    categoryLabel: "Hotel & Stay",
    address: "Apollo Bunder, Colaba, Mumbai 400001",
    latitude: 18.9217,
    longitude: 72.8332,
    source: "curated",
    rawType: "hotel",
  },
];

export const CURATED_BENGALURU_PLACES: Place[] = [
  {
    id: "blr-hist-1",
    name: "Bangalore Palace",
    category: "historical",
    categoryLabel: "Historical Landmark",
    address: "Vasanth Nagar, Bengaluru 560052",
    latitude: 12.9988,
    longitude: 77.5921,
    source: "curated",
    rawType: "palace",
  },
  {
    id: "blr-park-1",
    name: "Lalbagh Botanical Garden",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Mavalli, Bengaluru 560004",
    latitude: 12.9507,
    longitude: 77.5848,
    source: "curated",
    rawType: "botanical_garden",
  },
  {
    id: "blr-park-2",
    name: "Cubbon Park",
    category: "park",
    categoryLabel: "Park & Public Space",
    address: "Kasturba Road, Sampangi Rama Nagara, Bengaluru 560001",
    latitude: 12.9764,
    longitude: 77.5929,
    source: "curated",
    rawType: "park",
  },
  {
    id: "blr-rest-1",
    name: "Mavalli Tiffin Room (MTR)",
    category: "restaurant",
    categoryLabel: "Restaurant & Cafe",
    address: "Lalbagh Main Rd, Doddamavalli, Sudhama Nagar, Bengaluru 560027",
    latitude: 12.9553,
    longitude: 77.5862,
    source: "curated",
    rawType: "restaurant",
  },
  {
    id: "blr-hotel-1",
    name: "The Leela Palace Bengaluru",
    category: "hotel",
    categoryLabel: "Hotel & Stay",
    address: "Old Airport Rd, HAL 2nd Stage, Kodihalli, Bengaluru 560008",
    latitude: 12.9606,
    longitude: 77.6484,
    source: "curated",
    rawType: "hotel",
  },
];

export const CURATED_CITY_PLACES: Record<string, Place[]> = {
  Pune: CURATED_PUNE_PLACES,
  Mumbai: CURATED_MUMBAI_PLACES,
  Bengaluru: CURATED_BENGALURU_PLACES,
};

// Open-Meteo WMO weather code descriptions
export const WMO_WEATHER_CODES: Record<number, { text: string; icon: string }> = {
  0: { text: "Clear sky", icon: "sun" },
  1: { text: "Mainly clear", icon: "sun" },
  2: { text: "Partly cloudy", icon: "cloud-sun" },
  3: { text: "Overcast", icon: "cloud" },
  45: { text: "Foggy", icon: "cloud-fog" },
  48: { text: "Depositing rime fog", icon: "cloud-fog" },
  51: { text: "Light drizzle", icon: "cloud-drizzle" },
  53: { text: "Moderate drizzle", icon: "cloud-drizzle" },
  55: { text: "Dense drizzle", icon: "cloud-drizzle" },
  61: { text: "Slight rain", icon: "cloud-rain" },
  63: { text: "Moderate rain", icon: "cloud-rain" },
  65: { text: "Heavy rain", icon: "cloud-rain-heavy" },
  71: { text: "Slight snow fall", icon: "snowflake" },
  73: { text: "Moderate snow fall", icon: "snowflake" },
  75: { text: "Heavy snow fall", icon: "snowflake" },
  80: { text: "Slight rain showers", icon: "cloud-rain" },
  81: { text: "Moderate rain showers", icon: "cloud-rain" },
  82: { text: "Violent rain showers", icon: "cloud-rain-heavy" },
  95: { text: "Thunderstorm", icon: "cloud-lightning" },
  96: { text: "Thunderstorm with slight hail", icon: "cloud-lightning" },
  99: { text: "Thunderstorm with heavy hail", icon: "cloud-lightning" },
};
